Tomek Ukowski
---
- name: Deploy DVWA to Kubernetes
  hosts: localhost
  vars:
    kubeconfig: " ~/.kube/config"
    context: "arn:aws:eks:us-east-1:448323382078:cluster/DVWA_Cluster"
    namespace: "default"
    image_name: "dvwa"
    image_version: "latest"
    registry: "docker.io"
  tasks:
    - name: Create Deployment
      k8s:
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ context }}"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: dvwa
            namespace: "{{ namespace }}"
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: dvwa
            template:
              metadata:
                labels:
                  app: dvwa
              spec:
                containers:
                  - name: dvwa
                    image: "{{ registry }}/{{ image_name }}:{{ 
image_version }}"
                    ports:
                      - containerPort: 80
    - name: Create Service
      k8s:
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ context }}"
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: dvwa-service
            namespace: "{{ namespace }}"
          spec:
            selector:
              app: dvwa
            type: LoadBalancer
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
