---
- name: Deploy Falco
  hosts: localhost
  tasks:
  - name: Add Falco chart repo
    kubernetes.core.helm_repository:
      name: falcosecurity
      repo_url: "https://falcosecurity.github.io/charts"

  - name: Deploy latest version of Falco
    kubernetes.core.helm:
      name: falco
      chart_ref: falcosecurity/falco
      release_namespace: falco
      create_namespace: true
      values:
        ebpf.enabled: true

  - name: Patch Falco daemonset
    shell: kubectl -n falco patch daemonset falco --patch '{"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"falco"}],"containers":[{"name":"falco","tty":true}]}}}}'
