---
- name: Deploy NGINX
  hosts: localhost
  tasks:
  - name: Create deployment file
    copy:
      dest: "deployment.yaml"
      content: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          namespace: default
          name: nginx2
          labels:
            app: nginx2
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: nginx2
          template:
            metadata:
              labels:
                app: nginx2
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: beta.kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
              containers:
              - name: nginx
                image: nginx:1.19.2
                ports:
                - containerPort: 80
    
  - name: Apply deployment
    kubernetes.core.k8s:
      state: present
      src: deployment.yaml

      