---
- name: Remove App deployment
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Deployment
    namespace: default
    name: nginx

- name: Remove Falco
  kubernetes.core.helm:
    name: falco
    state: absent
    wait: true
    release_namespace: falco